/**
 * 所有的 action 类型
*/
export default {
    LOGIN_PENDING: 'LOGIN_PENDING',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_ERROR: 'LOGIN_ERROR',
    LOGOUT_PENDING: 'LOGOUT_PENDING',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAIL: 'LOGOUT_FAIL',
    REGISTER_PENDING: 'REGISTER_ING',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_ERROR: 'REGISTER_ERROR',
    UPLOAD_PICTURE_PENDING: 'UPLOAD_PICTURE_PENDING',
    UPLOAD_PICTURE_SUCCESS: 'UPLOAD_PICTURE_SUCCESS',
    UPLOAD_PICTURE_FAIL: 'UPLOAD_PICTURE_FINISH',
    GET_PICTURES_PENDING: 'GET_PICTURES_PENDING',
    GET_PICTURES_SUCCESS: 'GET_PICTURES_SUCCESS',
    GET_PICTURES_FAIL: 'GET_PICTURES_FAIL',
    DELETE_PICTURE_PENDING: 'DELETE_PICTURE_PENDING',
    DELETE_PICTURE_SUCCESS: 'DELETE_PICTURE_SUCCESS',
    DELETE_PICTURE_FAIL: 'DELETE_PICTURE_FAIL'
}
