/**
 * 所有的 action 类型
*/
export default {
    LOADING: 'LOADING',
    ERROR: 'ERROR',
    LOGIN: 'LOGIN',
    LOGIN_PENDING: 'LOGIN_PENDING',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_ERROR: 'LOGIN_ERROR',
    LOGOUT: 'LOGOUT',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    REGISTER: 'REGISTER',
    REGISTER_ING: 'REGISTER_ING',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_ERROR: 'REGISTER_ERROR',
    DASHBOARD: 'DASHBOARD',
    SEARCH_JIRA_ISSUE: 'SEARCH_JIRA_ISSUE',
    SEARCH_JIRA_ISSUE_PENDING: 'SEARCH_JIRA_ISSUE_PENDING',
    SEARCH_JIRA_ISSUE_SUCCESS: 'SEARCH_JIRA_ISSUE_SUCCESS',
    SEARCH_JIRA_ISSUE_FAIL: 'SEARCH_JIRA_ISSUE_FAIL',
    FILTER_JIRA_ISSUE_SUCCESS: 'FILTER_JIRA_ISSUE_SUCCESS',
    UPLOAD_PICTURE_PENDING: 'UPLOAD_PICTURE_PENDING',
    UPLOAD_PICTURE_SUCCESS: 'UPLOAD_PICTURE_SUCCESS',
    UPLOAD_PICTURE_FAIL: 'UPLOAD_PICTURE_FINISH',
    GET_PICTURES_PENDING: 'GET_PICTURES_PENDING',
    GET_PICTURES_SUCCESS: 'GET_PICTURES_SUCCESS',
    GET_PICTURES_FAIL: 'GET_PICTURES_FAIL'
}
